#!/bin/bash

# Otros
# post-merge: Después de realizar un git merge.
# Se ejecuta después de que se realiza un git merge. Es útil para realizar tareas como la compilación del código o la actualización de dependencias.
# `$ git merge`

echo "FILE '.githooks/post-merge' START"

# # Obtener la rama actual después de la fusión
# current_branch=$(git rev-parse --abbrev-ref HEAD)

# # Verificar si estamos en la rama 'main' y si es una fusión
# if [ "$current_branch" = "main" ]; then
#     echo "Has fusionado con la rama 'main'."
#     exit 1
# fi

# # Verificar si estamos en la rama 'preprod' y si es una fusión
# if [ "$current_branch" = "preprod" ]; then
#     echo "Has fusionado con la rama 'preprod'."
#     exit 1
# fi

# # Verificar si estamos en la rama 'production' y si es una fusión
# if [ "$current_branch" = "production" ]; then
#     echo "Has fusionado con la rama 'production'."
#     exit 1
# fi


# Permitir la operación
echo "FILE '.githooks/post-merge' END :)"
exit 0
