#!/bin/bash

# Obtener la rama en la que estamos intentando hacer commit
branch_name=$(git rev-parse --abbrev-ref HEAD)

# Verificar si estamos en un proceso de fusión
# `MERGING` es un estado que puede ser reconocido si hay un archivo en el directorio `.git` llamado `MERGE_HEAD`
if [ "$branch_name" = "main" ] || [ -f .git/MERGE_HEAD ]; then
    # Permitir commit si estamos en la rama 'main' o en un estado de fusión
    exit 0
else
    # Evitar commit en otras ramas
    echo "No puedes hacer commits directos en ramas distintas a 'main' a menos que estés en una fusión."
    exit 1
fi

# Verificar si estamos en un proceso de fusión
# `MERGING` es un estado que puede ser reconocido si hay un archivo en el directorio `.git` llamado `MERGE_HEAD`
if [ "$branch_name" = "preproduction" ] || [ -f .git/MERGE_HEAD ]; then
    # Permitir commit si estamos en la rama 'preproduction' o en un estado de fusión
    exit 0
else
    # Evitar commit en otras ramas
    echo "No puedes hacer commits directos en ramas distintas a 'preproduction' a menos que estés en una fusión."
    exit 1
fi

# Verificar si estamos en un proceso de fusión
# `MERGING` es un estado que puede ser reconocido si hay un archivo en el directorio `.git` llamado `MERGE_HEAD`
if [ "$branch_name" = "production" ] || [ -f .git/MERGE_HEAD ]; then
    # Permitir commit si estamos en la rama 'production' o en un estado de fusión
    exit 0
else
    # Evitar commit en otras ramas
    echo "No puedes hacer commits directos en ramas distintas a 'production' a menos que estés en una fusión."
    exit 1
fi


# Permitir el commit si no estamos en la rama 'main'
# exit 0