#!/bin/bash

echo "FILE '.githooks/pre-commit' START"



# Impedir poder hacer commits directos a la rama 'main, preprod, production'
# ---------------------------------------------------------
# Obtener la rama en la que estamos intentando hacer commit
branch_name=$(git rev-parse --abbrev-ref HEAD)

# Verificar si estamos en la rama 'main' o si estamos en un proceso de fusión
if [ "$branch_name" = "main" ] && [ ! -f .git/MERGE_HEAD ]; then
    echo "No puedes hacer commits directos a la rama 'main'."
    exit 1
fi

# Verificar si estamos en la rama 'preprod' o si estamos en un proceso de fusión
if [ "$branch_name" = "preprod" ] && [ ! -f .git/MERGE_HEAD ]; then
    echo "No puedes hacer commits directos a la rama 'preprod'."
    exit 1
fi

# Verificar si estamos en la rama 'production' o si estamos en un proceso de fusión
if [ "$branch_name" = "production" ] && [ ! -f .git/MERGE_HEAD ]; then
    echo "No puedes hacer commits directos a la rama 'production'."
    exit 1
fi
# ---------------------------------------------------------


# Permitir commit si no estamos en la rama 'main, preprod, production', o si estamos en una fusión
echo "FILE '.githooks/pre-commit' END :)"
exit 0
