#!/bin/bash

# Obtener la rama en la que estamos intentando hacer commit
branch_name=$(git rev-parse --abbrev-ref HEAD)

# Verificar si estamos en la rama 'main' o si estamos en un proceso de fusión
if [ "$branch_name" = "main" ] && [ ! -f .git/MERGE_HEAD ]; then
    echo "No puedes hacer commits directos a la rama 'main'."
    exit 1
fi

# Permitir commit si no estamos en la rama 'main', o si estamos en una fusión
echo "FIN pre-commit"
exit 0
